baseURL = "https://plsource.org/"
languageCode = "en-us"
title = "PLSource by OpenPowerlifting"
theme = "slate"

[ params ]
BackgroundStyle = "#657383;"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "primary"
tag = "primary"
icon = "star"
